---
title: "Conclusiones"
---

El Estudio de Notas de la Facultad de Ciencias Sociales ha entregado luces acerca de cómo se distribuyen las calificaciones, enfocándose en los estudiantes y cursos a partir de un nivel agregado de facultad, como también en las dinámicas de cada carrera. Así, los resultados observados permiten responder las preguntas que fueron planteadas en la introducción del reporte. 

**¿Existe la inflación de notas en la Facultad de Ciencias Sociales?** 

A partir de los elementos que circunscriben el análisis, se encontró evidencia que puede sustentar la hipótesis de inflación de notas. El alza pronunciada de las notas en los años 2020 y 2021 en comparación de años prepandémicos y su persistencia hasta el año 2025 demuestran que FACSO atraviesa un proceso que actualmente está presente en la educación superior a nivel global. 

**¿Las notas permiten discriminar grupos de estudiantes en función del rendimiento?**

Las calificaciones dificultan realizar una distinción entre estudiantes que sobresalen académicamente de aquellos que necesitan apoyo para cumplir con los aprendizajes esperados debido a la baja variabilidad de las notas que obtienen los estudiantes. Incluso, las calificaciones han tendido a homogeneizarse con el paso del tiempo, complicando aún más la tarea de diferenciar grupos de estudiantes a partir de su rendimiento académico. Esto es sumamente preocupante, ya que no se cuenta con la información necesaria para gestionar e implementar políticas enfocadas en estudiantes que requieren un apoyo adicional en su trayectoria académica, con el objetivo de reducir las brechas educativas de base. 

**¿Qué tan alto es el nivel de exigencia en cuánto a la aprobación de asignaturas?**

Los niveles de exigencia de los cursos en FACSO pueden entenderse como bajos, puesto que entre 2018 y 2025 el promedio de aprobación de los cursos fue de un 97%. Esto significa que reprobar un curso es una experiencia anómala, donde no hay mayores dificultades en acreditar la obtención de los conocimientos esperados de un ramo.

**¿Qué factores asociados dan cuenta de las notas, el grado de discriminación y la tasa de aprobación?**

En primer lugar, factores socioeconómicos como el tipo de colegio y el nivel socioeconómico demostraron ser determinantes en las calificaciones de los estudiantes. En segundo lugar, el género evidenció tener un rol explicativo importante, donde las mujeres tienen un rendimiento más alto que su contraparte. En tercer lugar, variables institucionales como el tipo de curso y el tamaño del curso se confirmaron como factores asociados a las calificaciones.

Considerando el conjunto de estos hallazgos se asoma como un imperativo desarrollar una discusión seria sobre el panorama actual de la dimensión formativa-evaluativa de la facultad: en un contexto de inflación de notas, el hecho que las evaluaciones no hagan posible diferenciar a grupos de estudiantes puede tener consecuencias graves en la población estudiantil, como sentimientos de injusticia en la calificación académica. Además, se podría hipotetizar una carencia formativa de los estudiantes, pero precisamente la alta homogeneidad en las calificaciones no permite identificar si tales carencias existen.

En el marco de la incorporación de normativas que promulgan la no discriminación y la equidad, hay que tener suma precaución con que estos principios no se confundan con la capacidad de capturar las diferencias sociales y académicas que, como institución de excelencia, la Universidad de Chile debe ser capaz de observar y abordar apropiadamente. Por ello, es un deber institucional generar estrategias que puedan comprender cómo se plantean y despliegan las evaluaciones a estudiantes. Con todo, este estudio representa un diagnóstico de las dinámicas en las calificaciones académicas, y puede significar un insumo sumamente valioso para las autoridades al momento de promover de manera enfocada los recursos necesarios para pulir los sistemas de evaluación y, en última instancia, acortar las brechas en el logro académico de los estudiantes.

En el futuro, este estudio podría entregar más pistas sobre las calificaciones en la facultad a partir de la incorporación de información nueva. En este contexto, contar con las evaluaciones docentes y los cursos impartidos a lo largo del tiempo podrían aportar a caracterizar con mayor profundidad qué cursos cuentan con mayores tasas de aprobación, y cómo eso se relaciona con el juicio que realizan los estudiantes de los cursos. Asimismo, sería valioso realizar un estudio comparativo de los criterios de evaluación que declaran los cursos de cada carrera en sus programas, puesto que se podrían mapear los modos de capturar los aprendizajes, la asignación de métricas y los umbrales que determinan el éxito del proceso. Como última propuesta, replicar el este estudio en otras facultades significaría un avance en la comprensión del escenario formativo-evaluativo a nivel Universidad de Chile, ya que permitiría comparar las diferencias entre facultades que forman parte de un mismo ecosistema académico. 



 




